import "./third-party-notices.mjs";
import { createRequire } from "node:module";
import { writeFile } from "node:fs/promises";
import { cardPolicySchema } from "../src/card-policy-schema.js";
import { manifestSchema, sceneSchema } from "../src/presentation/schema.js";
for (const [path, schema] of [
  ["../docs/card-policy.schema.json", cardPolicySchema],
  ["../docs/complex-cards/schemas/manifest.schema.json", manifestSchema],
  ["../docs/complex-cards/schemas/scene.schema.json", sceneSchema],
])
  await writeFile(
    new URL(path, import.meta.url),
    JSON.stringify(schema, null, 2) + "\n",
  );
import { fileURLToPath } from "node:url";
const require = createRequire(
  new URL("../src/presentation/package.json", import.meta.url),
);
const { build } = require("esbuild");
await build({
  entryPoints: [
    fileURLToPath(
      new URL("../src/presentation/layered-worker.js", import.meta.url),
    ),
  ],
  outfile: fileURLToPath(
    new URL("../src/presentation/layered-worker-bundle.js", import.meta.url),
  ),
  bundle: true,
  platform: "browser",
  format: "esm",
  external: ["node:*"],
  target: "es2022",
  minify: true,
  legalComments: "inline",
  banner: {
    js: "// Generated by tools/build-fonts.mjs from pinned presentation dependencies.",
  },
});
await build({
  entryPoints: [
    fileURLToPath(
      new URL("../src/presentation/font-source.js", import.meta.url),
    ),
  ],
  outfile: fileURLToPath(
    new URL("../src/presentation/font-engine.js", import.meta.url),
  ),
  bundle: true,
  platform: "browser",
  format: "esm",
  target: "es2022",
  minify: true,
  legalComments: "inline",
  banner: {
    js: "// Generated by tools/build-fonts.mjs from the pinned fontkit dependency.",
  },
});
