import {createAdminController} from './admin-client.js';
import {adminCSS} from './admin-styles.js';
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text);return n;};
const btn=(text,action,kind='')=>{const n=el('button','da-button '+kind,text);n.type='button';n.addEventListener('click',action);return n;};
const actions=(...items)=>{const n=el('div','da-actions');n.append(...items);return n;};
const pill=(text,live=true)=>el('span','da-pill '+(live?'is-live':'is-paused'),text);
const nameOf=item=>item?.displayName??item?.name??'Unnamed account';
const readable=value=>value===null||value===undefined?'Default':typeof value==='boolean'?(value?'On':'Off'):String(value);
function field(parent,label,{value='',type='text',help='',min,max,step}={}){const wrap=el('label','da-field'),input=el(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.value=String(value);input.setAttribute('aria-label',label);for(const [key,val]of Object.entries({min,max,step}))if(val!==undefined)input[key]=String(val);wrap.append(el('span','',label),input);if(help)wrap.append(el('small','',help));parent.append(wrap);return input;}
function select(parent,label,items,value){const wrap=el('label','da-field'),input=el('select');input.setAttribute('aria-label',label);for(const item of items){const option=el('option','',item.name);option.value=item.id;input.append(option);}if(value!==undefined)input.value=value;wrap.append(el('span','',label),input);parent.append(wrap);return input;}
function toggle(parent,title,description,enabled){const row=el('div','da-switch-row'),text=el('div'),wrap=el('label','da-toggle'),input=el('input'),state=el('span','',enabled?'Allowed':'Paused');input.type='checkbox';input.checked=enabled;input.setAttribute('aria-label',title);input.addEventListener('change',()=>{state.textContent=input.checked?'Allowed':'Paused';});text.append(el('strong','',title),el('small','',description));wrap.append(input,state);row.append(text,wrap);parent.append(row);return input;}
function empty(parent,title,text){const box=el('div','da-empty');box.append(el('h3','',title),el('p','',text));parent.append(box);}
function heading(parent,title,description){const box=el('div','da-heading'),text=el('div');text.append(el('h2','',title),el('p','',description));box.append(text);parent.append(box);return box;}
function change(label,before,after){return {label,before:readable(before),after:readable(after)};}

/** Optional default view; hosts can use the controller without this markup. */
export function mountAdminPanel(root,{client,controller:provided,namespace,storage,uiState={},navigate}={}){
  const node=el('section','dc-admin');node.setAttribute('aria-label','Admin control panel');root.append(node);
  const style=el('style');style.textContent=adminCSS;node.append(style);
  const top=el('header','da-top'),brand=el('div','da-brand'),brandText=el('div');brandText.append(el('strong','','Admin control panel'),el('small','','Your community, under control.'));const mark=el('span','da-mark','◇');mark.setAttribute('aria-hidden','true');brand.append(mark,brandText);
  const mode=el('div','da-mode');mode.setAttribute('aria-label','Control complexity');top.append(brand,mode);node.append(top);
  const shell=el('div','da-shell'),nav=el('nav','da-nav'),main=el('div','da-main');nav.setAttribute('aria-label','Admin sections');shell.append(nav,main);node.append(shell);
  const ui=Object.assign({tab:'overview',advanced:false,lineId:null,productId:null,userId:null,peopleSearch:'',lineSearch:''},uiState);
  let controller=provided,disposed=false,unsubscribe=null,current=null,dirty=false,leave=null;
  const preserve=()=>Object.assign(uiState,ui);
  function move(fn){if(current?.pending||current?.phase==='saving')return;if(dirty||current?.review){leave=fn;showLeave();return;}fn();preserve();render();}
  function showLeave(){main.querySelector('.da-leave')?.remove();const box=el('div','da-status da-leave');box.setAttribute('role','alert');box.append(el('strong','','You have an unsaved draft.'),el('p','','Keep editing, or discard it before leaving.'),actions(btn('Keep editing',()=>{leave=null;box.remove();}),btn('Discard draft and continue',()=>{const next=leave;leave=null;dirty=false;controller.cancel();next?.();preserve();render();},'da-danger')));main.prepend(box);box.querySelector('button')?.focus();}
  function go(tab){move(()=>{ui.tab=tab;if(tab==='people'&&!ui.userId)controller.users({search:ui.peopleSearch});if(tab==='activity')controller.history();});}
  const tabs=[['overview','Overview','◉'],['lines','Card lines','▤'],['people','People','♙'],['website','Website','◎'],['activity','Activity','↺']];
  for(const [id,label,icon]of tabs){const b=btn('',()=>go(id));b.dataset.adminTab=id;const i=el('span','da-nav-icon',icon);i.setAttribute('aria-hidden','true');b.append(i,el('span','',label));nav.append(b);}nav.append(el('p','da-nav-note','Changes stay as drafts until you review and save them.'));
  for(const [advanced,label]of [[false,'Basic'],[true,'Advanced']]){const b=btn(label,()=>move(()=>{ui.advanced=advanced;}));b.dataset.adminMode=String(advanced);mode.append(b);}
  function stage(spec){dirty=false;controller.stage(spec);main.querySelector('.da-review h3')?.focus();}
  function form(title,description,build,submit){const box=el('form','da-form'),body=el('div','da-form-body'),footer=el('div','da-form-footer'),label=el('span','da-draft-label','Saved settings · no changes'),review=btn('Review changes',()=>{},'da-primary'),cancel=btn('Cancel',()=>{dirty=false;render();});review.type='submit';review.disabled=true;body.append(el('h3','',title));if(description)body.append(el('p','da-muted',description));const fields=build(body);footer.append(label,actions(cancel,review));box.append(body,footer);for(const event of ['input','change'])box.addEventListener(event,()=>{dirty=true;label.textContent='Unsaved draft · nothing has changed yet';review.disabled=false;});box.addEventListener('submit',event=>{event.preventDefault();if(!box.reportValidity())return;try{submit(fields);}catch(error){let msg=body.querySelector('.da-form-error');if(!msg){msg=el('p','da-form-error');msg.setAttribute('role','alert');body.append(msg);}msg.textContent=error.message;}});main.append(box);return box;}
  const rarityName=id=>current?.overview?.rarities?.find(r=>r.id===id)?.name??id;
  const currencyName=id=>current?.overview?.currencies?.find(c=>c.id===id)?.name??id;
  const staleError=error=>/ADMIN_CHANGED|STALE|REVISION/.test(error?.code??'');
  function status(){if(!current)return;if(current.message){const message=el('div','da-status',current.message);message.setAttribute('role','status');message.dataset.kind=current.pending?'warning':'success';main.append(message);}if(current.error){const error=el('div','da-status');error.dataset.kind='error';error.setAttribute('role','alert');const stale=staleError(current.error);error.append(el('strong','',stale?'Settings changed while you were editing.':'We could not finish that request.'),el('p','',stale?'Reload current settings, then review your changes again.':current.error.message));if(!current.pending)error.append(actions(btn('Reload current settings',()=>{dirty=false;controller.cancel();controller.load({keepReview:false});})));main.append(error);}}
  function render(){if(disposed)return;for(const b of nav.querySelectorAll('button')){b.setAttribute('aria-current',b.dataset.adminTab===ui.tab?'page':'false');b.disabled=!!current?.pending||current?.phase==='saving';}for(const b of mode.querySelectorAll('button')){b.setAttribute('aria-pressed',String(b.dataset.adminMode===String(ui.advanced)));b.disabled=!!current?.pending||current?.phase==='saving';}main.replaceChildren();status();if(!current?.overview){empty(main,current?.phase==='error'?'Admin panel unavailable':'Loading your controls…',current?.phase==='error'?'Your account may need administrator permissions.':'Checking the saved settings and your access.');return;}if(current.review){renderReview();return;}if(current.phase==='loading'){empty(main,'Refreshing settings…','Your saved controls will appear in a moment.');return;}({overview:renderOverview,lines:renderLines,people:renderPeople,website:renderWebsite,activity:renderActivity}[ui.tab]??renderOverview)();if(ui.advanced){const info=el('details');info.append(el('summary','','Technical details'),el('p','da-technical','Admin revision '+current.overview.revision));if(navigate)info.append(actions(btn('Open trading policy',()=>move(()=>navigate('tradingControls')))));main.append(info);}const permission=ui.tab==='people'&&ui.personAction?'cards':'manage';if(current.overview.permissions?.[permission]===false){for(const control of main.querySelectorAll('.da-form input,.da-form select,.da-form textarea,.da-form button'))control.disabled=true;main.append(el('p','da-note','Your account can view these settings. Additional administrator permission is required to change them.'));}}
  function renderReview(){const review=current.review,box=el('section','da-review');box.setAttribute('aria-label','Review changes');const title=el('h3','','Review: '+review.title);title.tabIndex=-1;box.append(el('span','da-eyebrow','REVIEW BEFORE SAVING'),title,el('p','da-muted',review.description||'Check exactly what will change. Nothing is applied until you save.'));const wrap=el('div','da-table-wrap'),table=el('table'),head=el('thead'),row=el('tr');for(const label of ['Setting','Saved','After saving'])row.append(el('th','',label));head.append(row);const body=el('tbody');for(const item of review.changes){const r=el('tr');r.append(el('td','',item.label),el('td','',item.before),el('td','',item.after));body.append(r);}table.append(head,body);wrap.append(table);box.append(wrap);if(review.input.reason)box.append(el('p','da-muted','Reason: '+review.input.reason));if(review.command==='administerCards')box.append(el('p','da-review-warning',review.input.action==='remove'?'Removal retires the selected copies and cannot be undone by this panel.':'New copies will be issued and may trigger their configured opening rewards.'));const save=btn(current.phase==='saving'?'Saving…':current.pending?'Retry same change':'Save changes',()=>controller.confirm(),'da-primary');save.disabled=current.phase==='saving'||!!(staleError(current.error)&&!current.pending)||current.overview.permissions?.[review.command==='administerCards'?'cards':'manage']===false;const cancel=btn('Cancel',()=>{dirty=false;controller.cancel();});cancel.disabled=current.pending||current.phase==='saving';box.append(actions(cancel,save));main.append(box);}
  function renderOverview(){heading(main,'A clear view of your community','Keep the essentials running. Make a change only when you need to.');const s=current.overview.site,paused=[s.packPurchasesPaused&&'pack purchases',s.tradingPaused&&'trading',s.playerShopsPaused&&'user shops'].filter(Boolean),banner=el('div','da-banner'),dot=el('span','da-status-dot'+(paused.length?' is-paused':'')),text=el('div');text.append(el('h3','',paused.length?'Some activity is paused':'No emergency pauses active'),el('p','',paused.length?'Paused: '+paused.join(', ')+'. Existing cards and records stay intact.':'Your emergency switches are clear. Individual line, account and host policies still apply.'));banner.append(dot,text);main.append(banner);const metrics=el('div','da-grid da-metrics');for(const [label,value]of [['Card lines',current.overview.lines.length],['Pack types',current.overview.lines.reduce((n,l)=>n+l.products.length,0)],['Accounts',current.overview.counts?.users??'—']]){const box=el('div','da-card');box.append(el('span','da-metric',value),el('span','da-metric-label',label));metrics.append(box);}main.append(metrics);const cards=el('div','da-grid');for(const [title,description,label,tab]of [['Manage your card lines','Set pack prices, run a discount or pause sales.','Manage card lines','lines'],['Help a person','Control permissions and correct their card inventory.','Find a person','people'],['Control the website','Pause purchases or trading, and manage user shops.','Website controls','website']]){const c=el('article','da-card');c.append(el('h3','',title),el('p','',description),btn(label,()=>go(tab)));cards.append(c);}main.append(cards);}
  function renderWebsite(){
    heading(main,'Website controls','Simple switches for the activities your community can use.');const site=current.overview.site,effective=current.overview.effective??{};
    if(effective.commerceEnabled===false||effective.tradingPolicyEnabled===false){const note=el('div','da-status');note.append(el('strong','','A host policy also limits activity.'),el('p','da-muted',[effective.commerceEnabled===false?'Commerce is disabled in the host configuration.':'',effective.tradingPolicyEnabled===false?'The host trading policy is disabled.':''].filter(Boolean).join(' ')));main.append(note);}
    form('Community activity','Pausing stops new activity. People can still view their cards and cancel existing offers or listings.',body=>{
      const purchases=toggle(body,'Pack purchases','Allow people to buy new packs. Already owned packs can still be opened.',!site.packPurchasesPaused);
      const trading=toggle(body,'Trading','Allow direct trades between people. This does not control marketplace sales.',!site.tradingPaused);
      const shops=toggle(body,'User shops','Allow community members to create shops and sell to each other. Account restrictions still apply.',effective.playerShops??(!site.playerShopsPaused&&site.playerShopsEnabled!==false));
      const reason=field(body,'Reason (optional)',{help:'A short note helps the next administrator understand the change.'});reason.maxLength=500;return {purchases,trading,shops,reason};
    },f=>{const changes={},rows=[];for(const [key,label,value]of [['packPurchasesPaused','Pack purchases',!f.purchases.checked],['tradingPaused','Trading',!f.trading.checked]])if(value!==site[key]){changes[key]=value;rows.push(change(label,site[key]?'Paused':'Allowed',value?'Paused':'Allowed'));}const shopBefore=effective.playerShops??(!site.playerShopsPaused&&site.playerShopsEnabled!==false);if(f.shops.checked!==shopBefore){changes.playerShopsEnabled=f.shops.checked;changes.playerShopsPaused=false;rows.push(change('User shops',shopBefore?'Allowed':'Disabled',f.shops.checked?'Allowed':'Disabled'));}if(!rows.length)throw new Error('No settings have changed.');stage({title:'Website controls',input:{scope:'site',changes,reason:f.reason.value.trim()||'Website activity settings updated'},changes:rows,description:'These controls apply across the website. Other catalog, account and host policies still apply.'});});
    if(ui.advanced){const card=el('section','da-card');card.append(el('h3','','Effective host policy'));for(const [label,value]of [['Direct trading',effective.directTrading],['User shops',effective.playerShops],['Commerce enabled',effective.commerceEnabled],['Trading policy enabled',effective.tradingPolicyEnabled]])card.append(el('p','',label+': '+(value===undefined?'Not reported':value?'Enabled':'Disabled')));card.append(el('p','da-note','Turning on an admin control cannot bypass disabled host capabilities or required ownership rules.'));main.append(card);}
  }
  function renderLines(){
    const lines=current.overview.lines,line=lines.find(l=>l.id===ui.lineId);
    if(!line){heading(main,'Card lines','Prices, sales and pack settings, grouped where they belong.');const searchBox=el('div','da-search'),search=field(searchBox,'Search card lines',{value:ui.lineSearch,type:'search'}),list=el('div','da-grid da-grid-two');main.append(searchBox,list);const draw=()=>{list.replaceChildren();const matches=lines.filter(l=>l.name.toLocaleLowerCase().includes(search.value.toLocaleLowerCase()));for(const line of matches){const box=el('article','da-card'),head=el('div','da-card-heading');head.append(el('h3','',line.name),pill(line.salesPaused?'Sales paused':'Sales allowed',!line.salesPaused));box.append(head,el('p','',line.products.length+' pack type'+(line.products.length===1?'':'s')),btn('Manage '+line.name,()=>move(()=>{ui.lineId=line.id;ui.productId=null;})));list.append(box);}if(!matches.length)empty(list,'No matching card lines','Try another name, or add a line through your catalog tools.');};search.addEventListener('input',()=>{ui.lineSearch=search.value;preserve();draw();});draw();return;}
    const product=line.products.find(p=>p.id===ui.productId);main.append(btn(product?'Back to '+line.name:'All card lines',()=>move(()=>{if(product)ui.productId=null;else ui.lineId=null;}),'da-text-button da-back'));if(product){renderProduct(line,product);return;}
    heading(main,line.name,'Manage sales for this line, or choose a pack to change its price and odds.');const sale=el('div','da-card'),head=el('div','da-card-heading');head.append(el('h3','','Sales for this card line'),pill(line.salesPaused?'Paused':'Allowed',!line.salesPaused));const control=btn(line.salesPaused?'Resume line sales':'Pause line sales',()=>stage({title:line.name+' sales',input:{scope:'line',targetId:line.id,changes:{salesPaused:!line.salesPaused},reason:line.salesPaused?'Line sales resumed':'Line sales paused'},changes:[change('Line sales',line.salesPaused?'Paused':'Allowed',line.salesPaused?'Allowed':'Paused')],description:'Applies to new pack purchases and marketplace sales containing this line.'}));control.disabled=current.overview.permissions?.manage===false;sale.append(head,el('p','',line.salesPaused?'New sales for this line are paused. Existing ownership stays intact.':'This line can be sold, subject to website and account policies.'),control);main.append(sale);
    const grid=el('div','da-grid da-grid-two');for(const pack of line.products){const box=el('article','da-card');box.append(el('h3','',pack.name),el('span','da-metric',pack.price.amount.toLocaleString()+' '+currencyName(pack.price.currencyId)),el('p','',pack.discountPercent?pack.discountPercent+'% discount active':'No discount'),el('small','da-muted',pack.catalogEnabled===false?'Disabled in catalog':line.salesPaused?'Sales paused':current.overview.site.packPurchasesPaused?'Pack purchases paused':'Available under normal rules'),btn('Edit '+pack.name,()=>move(()=>{ui.productId=pack.id;})));grid.append(box);}if(!line.products.length)empty(grid,'No packs in this line','Add a pack in your catalog to manage its pricing here.');main.append(grid);if(ui.advanced)main.append(el('p','da-technical','Line reference: '+line.id));
  }
  function renderProduct(line,product){
    heading(main,product.name,'Set a clear price. Review the result before making it live.');const oldAmount=product.priceAmount??product.basePrice?.amount??product.price.amount,oldDiscount=product.discountPercent??0;
    form('Pack pricing','Prices use whole currency units. Discounts affect new purchases only.',body=>{
      const fields=el('div','da-form-fields');body.append(fields);const price=field(fields,'Regular price',{type:'number',value:oldAmount,min:1,max:1000000000,step:1,help:currencyName(product.price.currencyId)}),discount=field(fields,'Discount (%)',{type:'number',value:oldDiscount,min:0,max:99,step:1,help:'Use 0 for the regular price.'});price.required=true;discount.required=true;
      const preview=el('div','da-preview-price'),amount=el('strong'),caption=el('small');preview.append(amount,caption);body.append(preview);const update=()=>{const p=Number(price.value),d=Number(discount.value);amount.textContent=Math.max(1,Math.floor(p*(100-d)/100)).toLocaleString()+' '+currencyName(product.price.currencyId);caption.textContent=d>0?'Buyer pays per pack · '+d+'% off':'Buyer pays per pack';};price.addEventListener('input',update);discount.addEventListener('input',update);update();
      const weights={};if(ui.advanced){body.append(el('h3','','Rarity weighting'),el('p','da-muted','Relative multipliers for future draws. 1 keeps the catalog weight; 0 excludes that rarity. Existing cards and already allocated packs do not change.'));const poolRarities=[...new Set((product.baseSlots??product.slots??[]).flatMap(s=>s.pool.map(entry=>current.overview.variants.find(v=>v.id===entry.variantId)?.rarityId).filter(Boolean)))],grid=el('div','da-form-fields');body.append(grid);for(const id of poolRarities){weights[id]=field(grid,rarityName(id)+' multiplier',{type:'number',value:product.rarityWeights?.[id]??1,min:0,max:1000,step:1});weights[id].required=true;}
        const odds=el('div','da-odds');body.append(odds);const updateOdds=()=>{odds.replaceChildren(el('strong','','Base share by draw pool'));for(const [index,slot]of (product.baseSlots??product.slots??[]).entries()){const totals={};for(const entry of slot.pool){const rarity=current.overview.variants.find(v=>v.id===entry.variantId)?.rarityId;if(rarity)totals[rarity]=(totals[rarity]??0)+entry.weight*Number(weights[rarity]?.value??1);}const sum=Object.values(totals).reduce((a,b)=>a+b,0);odds.append(el('p','da-muted','Pool '+(index+1)+' · '+slot.count+' draw'+(slot.count===1?'':'s')));for(const [id,weight]of Object.entries(totals)){const row=el('div','da-odds-row');row.append(el('span','',rarityName(id)),el('strong','',sum?(weight/sum*100).toFixed(1)+'%':'No eligible weight'));odds.append(row);}}};Object.values(weights).forEach(input=>input.addEventListener('input',updateOdds));updateOdds();body.append(el('p','da-note','These are base shares, not guaranteed outcomes. Remaining supply, duplicate protection and pity rules can change eligibility.'));}
      const reason=field(body,'Reason (optional)');reason.maxLength=500;return {price,discount,weights,reason};
    },f=>{const changes={},rows=[];if(Number(f.price.value)!==oldAmount){changes.priceAmount=Number(f.price.value);rows.push(change('Regular price',oldAmount+' '+currencyName(product.price.currencyId),changes.priceAmount+' '+currencyName(product.price.currencyId)));}if(Number(f.discount.value)!==oldDiscount){changes.discountPercent=Number(f.discount.value);rows.push(change('Discount',oldDiscount+'%',changes.discountPercent+'%'));}const weights=Object.fromEntries(Object.entries(f.weights).map(([id,input])=>[id,Number(input.value)]));if(Object.entries(weights).some(([id,value])=>value!==(product.rarityWeights?.[id]??1))){changes.rarityWeights=weights;for(const [id,value]of Object.entries(weights))if(value!==(product.rarityWeights?.[id]??1))rows.push(change(rarityName(id)+' multiplier',product.rarityWeights?.[id]??1,value));}if(!rows.length)throw new Error('No settings have changed.');rows.push(change('Buyer pays per pack',product.price.amount+' '+currencyName(product.price.currencyId),Math.max(1,Math.floor(Number(f.price.value)*(100-Number(f.discount.value))/100))+' '+currencyName(product.price.currencyId)));stage({title:product.name,input:{scope:'product',targetId:product.id,changes,reason:f.reason.value.trim()||'Pack settings updated'},changes:rows,description:'Applies to future purchases. Saved allocations and existing cards stay unchanged.'});});
    if(product.priceAmount!==null||oldDiscount||product.rarityWeights){const reset=btn('Reset pack settings to catalog',()=>move(()=>stage({title:'Reset '+product.name,input:{scope:'product',targetId:product.id,changes:{priceAmount:null,discountPercent:0,rarityWeights:null},reason:'Pack settings reset to catalog'},changes:[change('Pack price',product.price.amount+' '+currencyName(product.price.currencyId),product.basePrice.amount+' '+currencyName(product.price.currencyId)),change('Discount',oldDiscount+'%','0%'),change('Rarity weighting',product.rarityWeights?'Custom':'Catalog','Catalog')]})));reset.disabled=current.overview.permissions?.manage===false;main.append(reset);}if(ui.advanced)main.append(el('p','da-technical','Pack reference: '+product.id));
  }
  function renderPeople(){
    if(ui.userId){renderPerson();return;}heading(main,'People','Find a person, adjust what they can do, or help with their cards.');const searchBox=el('form','da-search'),search=field(searchBox,'Search people',{value:ui.peopleSearch,type:'search'}),find=btn('Find people',()=>{});find.type='submit';searchBox.append(find);searchBox.addEventListener('submit',event=>{event.preventDefault();ui.peopleSearch=search.value;preserve();controller.users({search:search.value});});main.append(searchBox);if(current.loadingUsers){empty(main,'Finding people…','Searching accounts by name.');return;}
    const list=el('div','da-grid da-grid-two');for(const user of current.users.items){const card=el('article','da-card'),head=el('div','da-card-heading'),blocked=Object.values(user.restrictions??{}).some(v=>v===true);head.append(el('h3','',nameOf(user)),pill(blocked?'Restrictions set':'No account blocks',!blocked));card.append(head,el('p','',(user.cardCount??0)+' cards · '+(user.packCount??0)+' packs'),btn('Manage '+nameOf(user),()=>move(()=>{ui.userId=user.id;ui.personAction=null;controller.person(user.id);})));if(ui.advanced||current.users.items.filter(other=>nameOf(other)===nameOf(user)).length>1)card.append(el('small','da-technical',user.id));list.append(card);}if(!current.users.items.length)empty(list,'No people found','Try another name. Accounts appear after joining this installation.');main.append(list);if(current.users.next)main.append(btn('Load more people',()=>controller.users({search:ui.peopleSearch,after:current.users.next})));
  }
  function renderPerson(){
    main.append(btn(ui.personAction?'Back to person':'All people',()=>move(()=>{if(ui.personAction)ui.personAction=null;else ui.userId=null;}),'da-text-button da-back'));if(current.loadingPerson||current.person?.user.id!==ui.userId){empty(main,'Loading this person…','Checking current permissions and card ownership.');return;}const person=current.person,user=person.user;heading(main,nameOf(user),'Changes here apply only to this person. Website and card policies still apply.');if(ui.personAction){renderInventoryAction(person);return;}
    const summary=el('div','da-card'),give=btn('Give cards',()=>move(()=>{ui.personAction='give';})),remove=btn('Remove cards',()=>move(()=>{ui.personAction='remove';}),'da-danger');give.disabled=remove.disabled=current.overview.permissions?.cards===false;summary.append(el('h3','','Card inventory'),el('p','',(user.cardCount??person.inventory.total??person.inventory.items.length)+' cards currently recorded'),actions(give,remove));main.append(summary);
    const restrictions=user.restrictions??{};form('What this person can do','Blocking a permission stops new activity. It does not delete their cards or hide their account.',body=>{const trading=toggle(body,'Allow trading','Direct trades with other people.',!restrictions.tradingBlocked),selling=toggle(body,'Allow selling','Create listings and sell through user shops.',!restrictions.sellingBlocked),buying=toggle(body,'Allow buying','Buy packs and marketplace items.',!restrictions.buyingBlocked),reason=field(body,'Reason (optional)');reason.maxLength=500;return {trading,selling,buying,reason};},f=>{const changes={},rows=[];for(const [key,label,input]of [['tradingBlocked','Trading',f.trading],['sellingBlocked','Selling',f.selling],['buyingBlocked','Buying',f.buying]])if(!input.checked!==!!restrictions[key]){changes[key]=!input.checked;rows.push(change(label,restrictions[key]?'Blocked':'Allowed',input.checked?'Allowed':'Blocked'));}if(!rows.length)throw new Error('No permissions have changed.');stage({title:nameOf(user)+' permissions',input:{scope:'user',targetId:user.id,changes,reason:f.reason.value.trim()||'Account permissions updated'},changes:rows});});if(ui.advanced)main.append(el('p','da-technical','Account reference: '+user.id));
  }
  function renderInventoryAction(person){
    const user=person.user,give=ui.personAction==='give';form(give?'Give cards':'Remove selected cards',give?'Create new copies for this person. Finite edition limits and card policies still apply.':'Choose the exact copies to retire. Cards reserved for an offer or listing cannot be removed.',body=>{let variant,quantity,checks=[];
      if(give){const variants=current.overview.variants.filter(v=>v.enabled!==false&&(v.remaining===null||v.remaining===undefined||v.remaining>0));variant=select(body,'Card to give',variants.map(v=>({id:v.id,name:v.name+' · '+rarityName(v.rarityId)+' · '+(current.overview.lines.find(l=>l.id===v.lineId)?.name??'')+(v.remaining!==null&&v.remaining!==undefined?' · '+v.remaining+' available':'')})));variant.required=true;quantity=field(body,'Number of cards',{type:'number',value:1,min:1,max:100,step:1});quantity.required=true;if(!variants.length)body.append(el('p','da-note','No enabled variants are available to give.'));}
      else{const list=el('div','da-checkboxes');for(const card of person.inventory.items){const wrap=el('label','da-checkbox-row'),input=el('input'),text=el('span'),removable=card.canRemove??card.removable??false;input.type='checkbox';input.value=card.id??card.copyId;input.disabled=!removable;input.setAttribute('aria-label','Remove '+card.name+(card.serialNumber?' number '+card.serialNumber:' copy '+(card.id??card.copyId).slice(0,8)));text.append(el('strong','',card.name),el('small','',rarityName(card.rarityId)+(card.serialNumber?' · No. '+card.serialNumber:' · Copy '+(card.id??card.copyId).slice(0,8))+(!removable?' · '+(card.blockedReason??'Unavailable for removal'):'')));wrap.append(input,text);list.append(wrap);checks.push(input);}body.append(list);if(!person.inventory.items.length)empty(body,'No cards to remove','This person does not own any cards.');if(person.inventory.next)body.append(btn('Load more cards',()=>move(()=>controller.person(user.id,{after:person.inventory.next}))));}
      const reason=field(body,'Reason for this inventory change',{type:'textarea',help:'Required. This note is saved in Activity.'});reason.required=true;reason.maxLength=500;return {variant,quantity,checks,reason};
    },f=>{const reason=f.reason.value.trim();if(!reason)throw new Error('Add a reason for changing this person’s inventory.');if(give){const variant=current.overview.variants.find(v=>v.id===f.variant.value);if(!variant)throw new Error('Choose an available card.');const quantity=Number(f.quantity.value);stage({command:'administerCards',title:'Give cards to '+nameOf(user),input:{userId:user.id,action:'give',variantId:variant.id,quantity,reason},changes:[change(variant.name+' · '+rarityName(variant.rarityId),'Current inventory','Add '+quantity+' new '+(quantity===1?'copy':'copies'))]});}else{const ids=f.checks.filter(input=>input.checked).map(input=>input.value);if(!ids.length)throw new Error('Select at least one available card to remove.');const selected=person.inventory.items.filter(c=>ids.includes(c.id??c.copyId));stage({command:'administerCards',title:'Remove cards from '+nameOf(user),input:{userId:user.id,action:'remove',copyIds:ids,reason},changes:selected.map(c=>change(c.name+' · '+rarityName(c.rarityId)+(c.serialNumber?' · No. '+c.serialNumber:' · Copy '+(c.id??c.copyId).slice(0,8)),'Owned by '+nameOf(user),'Retired from inventory'))});}});
  }
  function renderActivity(){
    heading(main,'Activity','A record of who changed settings and why.');main.append(btn('Refresh activity',()=>controller.history()));if(current.loadingHistory&&!current.history.items.length){empty(main,'Loading activity…','Fetching the administrator change history.');return;}const list=el('div','da-activity'),labels={packPurchasesPaused:'Pack purchases paused',tradingPaused:'Trading paused',playerShopsPaused:'User shops paused',playerShopsEnabled:'User shops enabled',salesPaused:'Line sales paused',priceAmount:'Regular price',discountPercent:'Discount (%)',tradingBlocked:'Trading blocked',sellingBlocked:'Selling blocked',buyingBlocked:'Buying blocked',rarityWeights:'Rarity weighting'};
    for(const item of current.history.items){const box=el('article','da-activity-item'),target=item.targetName??current.overview.lines.find(l=>l.id===item.targetId)?.name??current.overview.lines.flatMap(l=>l.products).find(p=>p.id===item.targetId)?.name??(item.scope==='site'?'Website':item.scope==='user'?'Account permissions':'Card inventory');box.append(el('strong','',target),el('small','','Changed by '+(item.actorName??'Administrator')+' · '+new Date(item.at).toLocaleString()),el('p','',item.reason||'Settings updated'));const details=el('details');details.append(el('summary','','See changes'));
      if(item.scope==='cards')details.append(el('p','da-muted',(item.before.action==='give'?'Added ':'Removed ')+item.before.quantity+' card'+(item.before.quantity===1?'':'s')));
      else for(const key of new Set([...Object.keys(item.before??{}),...Object.keys(item.after??{})])){const a=item.before?.[key],b=item.after?.[key];if(JSON.stringify(a)===JSON.stringify(b))continue;if(typeof a==='object'||typeof b==='object')details.append(el('p','da-muted',(labels[key]??'Inventory details')+' updated'));else details.append(el('p','da-muted',(labels[key]??key)+': '+readable(a)+' → '+readable(b)));}
      if(ui.advanced)details.append(el('p','da-technical','Change: '+item.id+' · Operator: '+item.actorId+(item.targetId?' · Target: '+item.targetId:'')));box.append(details);list.append(box);
    }if(!current.history.items.length)empty(list,'No admin changes yet','Saved settings and inventory changes will appear here.');main.append(list);if(current.history.next)main.append(btn('Load more activity',()=>controller.history({after:current.history.next})));
  }
  const ready=(async()=>{if(!controller){let actor=namespace;if(!actor){const me=await client.me();actor=me.userId;}if(disposed)return;let memory=storage;if(memory===undefined)try{memory=globalThis.sessionStorage;}catch{}controller=createAdminController({client,namespace:actor,storage:memory});}if(disposed)return;unsubscribe=controller.subscribe(state=>{current=state;render();});await controller.load();if(disposed)return;if(ui.tab==='people'){if(ui.userId)await controller.person(ui.userId);else await controller.users({search:ui.peopleSearch});}if(ui.tab==='activity')await controller.history();})().catch(error=>{if(!disposed){main.replaceChildren();const status=el('div','da-status',error.message);status.setAttribute('role','alert');main.append(status);}});
  return {node,ready,get controller(){return controller;},requestLeave:move,refresh:()=>{if(dirty||current?.review){move(()=>controller.load({keepReview:false}));return Promise.resolve();}return controller?.load();},dispose(){disposed=true;preserve();unsubscribe?.();if(!provided)controller?.dispose();node.remove();}};
}
export function renderAdminPanel(model,{client,state={},navigate}={}){
  const root=el('div');state.admin??={};const mounted=mountAdminPanel(root,{client,namespace:model.me.userId,uiState:state.admin,navigate});return {node:root,ready:mounted.ready,controller:()=>mounted.controller,requestLeave:mounted.requestLeave,dispose:()=>mounted.dispose()};
}
