import {el,button,select,section} from './ui-kit.js';
export function renderActivity(model,{client,action,mutate}){
  const node=section('Activity & account','Track exchanges, wallet changes and attached data. Choose how collectors can see your inventory.'),settings=el('div','dc-form-panel'),privacy=select(settings,'Inventory visibility',[{id:'private',name:'Private · only me'},{id:'traders',name:'Collectors while card trading is enabled'},{id:'public',name:'All signed-in collectors'}],model.me.preferences?.inventoryVisibility??'traders');
  settings.append(button('Save visibility',()=>action(()=>mutate('preferences',{inventoryVisibility:privacy.value}),{message:'Inventory visibility saved.'})));node.append(settings);
  let disposed=false;const notices=el('div','dc-activity-list'),history=el('div','dc-activity-list'),bindings=el('div','dc-binding-list');node.append(el('h3','dc-subheading','Notifications'),notices,el('h3','dc-subheading','Wallet ledger'),history,el('h3','dc-subheading','Your attached data'),bindings);
  async function load(){try{const [notificationPage,entries,attached,users]=await Promise.all([client.notifications({limit:100}),client.history(),client.bindings(),client.directory({limit:200})]);if(disposed)return;
    if(notificationPage.items.length){const unread=notificationPage.items.filter(n=>!n.read);if(unread.length)notices.append(button('Mark all shown as read',()=>action(()=>mutate('readNotifications',{ids:unread.map(n=>n.id)}),{message:'Notifications marked as read.'}),'dc-quiet'));
      for(const item of notificationPage.items){const row=el('div','dc-activity-row');row.append(el('span',item.read?'dc-muted':'dc-accent',item.type.replaceAll('.',' · ')),el('time','dc-muted',new Date(item.at).toLocaleString()));notices.append(row);}}
    else notices.append(el('p','dc-muted','You’re all caught up.'));
    for(const entry of entries.slice(-100).reverse()){const row=el('div','dc-activity-row');row.append(el('span','',entry.type),el('strong',entry.delta>=0?'dc-accent':'',`${entry.delta>=0?'+':''}${entry.delta.toLocaleString()} ${model.catalog.currencies.find(c=>c.id===entry.currencyId)?.name??entry.currencyId}`),el('small','dc-muted','Balance '+entry.balance.toLocaleString()),el('time','dc-muted',new Date(entry.at).toLocaleString()));history.append(row);}
    if(!entries.length)history.append(el('p','dc-muted','Wallet transactions will appear here.'));
    for(const binding of attached){const box=el('article','dc-form-panel');box.append(el('h4','',binding.namespace+' · '+binding.state),el('pre','dc-binding-data',JSON.stringify(binding.data,null,2)),el('small','dc-muted','Copy '+binding.copyId));if(binding.state==='active')box.append(button('Mark used',()=>action(()=>mutate('consumeBinding',{copyId:binding.copyId,namespace:binding.namespace}),{message:'Attached binding marked used. External redemption must be implemented by the host.'}),'dc-quiet'));bindings.append(box);}if(!attached.length)bindings.append(el('p','dc-muted','Owner-only codes and other attached data appear here when you receive them.'));
    const blocked=new Set(model.me.preferences?.blockedUserIds),blockOptions=[{id:'',name:'Choose collector…'},...users.items],block=select(settings,'Block incoming trades from',blockOptions);settings.append(button('Block collector',()=>action(()=>mutate('preferences',{blockedUserIds:[...blocked,block.value].filter(Boolean)}),{message:'Collector blocked.'}),'dc-quiet'));
    for(const id of blocked)settings.append(button('Unblock '+id.slice(0,8),()=>action(()=>mutate('preferences',{blockedUserIds:[...blocked].filter(x=>x!==id)}),{message:'Collector unblocked.'}),'dc-quiet'));
  }catch(err){if(!disposed)notices.append(el('p','dc-error',err.message));}}
  load();return {node,dispose(){disposed=true;}};
}
