import {el,button,field,select,section,previewCopy,download} from './ui-kit.js';
export function renderStudio(model,{client,cardRenderer,inspect,action,mutate}){
  const node=section('Creator studio','Import cards, stats, layered artwork references, pack definitions and combinations. Preview every change before publishing.');
  if(model.me.role!=='admin'){node.append(el('p','dc-muted','This workspace is available to authorized catalog operators.'));return node;}
  const options=el('div','dc-form-row'),format=select(options,'Format',[{id:'json',name:'JSON'},{id:'yaml',name:'YAML'}]),mode=select(options,'Import mode',[{id:'merge',name:'Merge rows by ID'},{id:'replace',name:'Replace complete catalog'}]),upload=field(options,'Choose file',{type:'file'});upload.accept='.json,.yaml,.yml,application/json';
  const source=field(node,'Import content',{type:'textarea',placeholder:'Paste JSON or YAML here. Rows with existing IDs replace those rows; omitted rows remain in merge mode.'});source.rows=14;source.spellcheck=false;source.classList.add('dc-code-input');
  const status=el('p','dc-muted'),preview=el('div','dc-import-preview'),review=el('label','dc-review-check'),confirm=el('input');confirm.type='checkbox';review.append(confirm,el('span','','I reviewed this catalog revision and its asset references.'));
  let prepared=null,generation=0,disposed=false;
  function invalidate(){generation++;prepared=null;confirm.checked=false;publish.disabled=true;preview.replaceChildren();status.textContent='Content changed. Run a new preview.';}
  const publish=button('Publish reviewed revision',()=>action(()=>mutate('commitImport',{manifest:prepared.manifest,digest:prepared.digest,expectedVersion:model.catalog.version}),{message:'Catalog revision published atomically.'}));publish.disabled=true;confirm.addEventListener('change',()=>publish.disabled=!confirm.checked||!prepared);
  const previewButton=button('Validate & preview',async()=>{const current=++generation;prepared=null;publish.disabled=true;confirm.checked=false;status.textContent='Validating…';try{const result=await client.previewImport({source:source.value,format:format.value,mode:mode.value,expectedVersion:model.catalog.version});if(disposed||generation!==current)return;prepared=result;preview.replaceChildren();status.textContent='Valid revision '+result.manifest.version+' · '+result.digest.slice(0,16)+' · No changes published yet.';
    const changes=el('div','dc-change-grid'),groups=new Map();for(const change of result.changes){if(!groups.has(change.section))groups.set(change.section,{add:[],update:[],remove:[]});groups.get(change.section)[change.action].push(change.id);}for(const [kind,change]of groups){const box=el('article','dc-change-box');box.append(el('h3','',kind),el('p','',`${change.add.length} added · ${change.update.length} updated · ${change.remove.length} removed`));for(const [type,ids]of Object.entries(change))if(ids.length)box.append(el('small','dc-muted',type+': '+ids.slice(0,30).join(', ')));changes.append(box);}preview.append(changes);
    for(const warning of result.warnings)preview.append(el('p','dc-muted',typeof warning==='string'?warning:warning.path+' · '+warning.message));const cards=el('div','dc-collection-grid');for(const card of result.manifest.cards.slice(0,24))cards.append(cardRenderer(previewCopy(card,result.manifest.variants.find(v=>v.cardId===card.id)),{onSelect:inspect}));preview.append(el('h3','','Card previews · first 24 definitions'),cards);
  }catch(err){if(!disposed&&generation===current)status.textContent=err.message;}});
  const controls=el('div','dc-row');controls.append(previewButton,publish,button('Export full JSON catalog',()=>action(async()=>download('catalog.json',await client.operatorCatalog()),{refreshAfter:false,message:'Catalog downloaded. Operator exports can contain binding definitions.'}),'dc-quiet'),button('Load starter row',()=>{format.value='json';mode.value='merge';source.value=JSON.stringify({cards:[{id:'your-card',lineId:model.catalog.lines[0]?.id,name:'Your first card',description:'Describe this collectible.',stats:{attack:7,defense:4},metadata:{'creator.credit':'Your name'},tags:['starter'],layers:[{id:'background',src:'https://your-content.example/card-background.webp',depth:0},{id:'foreground',src:'https://your-content.example/card-foreground.webp',depth:22}]}],variants:[{id:'your-card.standard',cardId:'your-card',rarityId:model.catalog.rarities[0]?.id,finish:'gloss'}]},null,2);invalidate();},'dc-quiet'));
  node.prepend(options);node.append(controls,status,review,preview,el('p','dc-muted','Asset files stay in your storage or CDN. Import URLs and manifests; keep reward codes in owner-only bindings. Published edition identities and limits remain fixed.'));
  for(const input of [source,format,mode])input.addEventListener('input',invalidate);upload.addEventListener('change',async()=>{const file=upload.files[0];if(!file)return;invalidate();const current=generation;if(file.size>8*1024*1024){status.textContent='Maximum import size is 8 MiB.';return;}const text=await file.text();if(disposed||current!==generation)return;source.value=text;format.value=/\.ya?ml$/i.test(file.name)?'yaml':'json';status.textContent='File loaded. Validate it to preview the revision.';});
  return {node,dispose(){disposed=true;generation++;}};
}
